### ISSUE TITLE
How to define multiple namespaces

### ISSUE THREAD

**Issue by mvhenderson** [intersystems/healthshare-sample-container-deploy#16]
How can I define multiple namespaces in the `feature-config`? I would have expected this to be an array not an object. Or do you expect to spin up a separate container for each namespace?

**Comment by isc-kiyer** [comment]
Each container stack supports a single namespace. This is intentional and by design. This is documented on https://docs.intersystems.com/hs20232/csp/docbook/DocBook.UI.Page.cls?KEY=HSDEPLOY_container.

**Comment by mvhenderson** [comment]
Thanks for the link - I didn't see that back in Dec.
