### ISSUE TITLE
Foundation

### ISSUE THREAD

**Issue by rleffmit** [intersystems/healthshare-sample-container-deploy#5]
Do we need a sample foundation namespace feature config? The docs include foundation because the installer wizard includes foundation, but there is no sample in the repo. https://docs.intersystems.com/hs202311/csp/docbook/DocBook.UI.Page.cls?KEY=HESUP_ch_foundation#HESUP_foundation_creating

**Comment by isc-kiyer** [comment]
Per Sebastian in teams (no samples for deploying foundation at this time...maybe in the future...probably not), we do not plan to support foundation namespaces for HS instances since those are intended for I4H/HC so closing this with no plans.
